### ISSUE TITLE
Varint tag

### ISSUE THREAD

**Issue by arj03** [arj03/minibutt-spec#4]
From #2:

> have you considered instead using a varint or similar, in case the far future needs more than 256 types of semantics? one promising candidate is https://en.wikipedia.org/wiki/LEB128

**Comment by arj03** [comment]
For now this field is removed because the semantics of tombstone was not clearly defined when you have a DAG instead of a linear structure.

**Comment by AljoschaMeyer** [comment]
Obligatory remark that LEB128 suffers from [easily avoidable issues](https://github.com/multiformats/unsigned-varint/issues/12) that everybody loves to ignore. Plugging [my own thingy](https://github.com/AljoschaMeyer/varu64) as an alternative of course.
